# Generated by Django 5.1.3 on 2024-12-09 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_orderitem_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='odreder_date',
            new_name='ordered_date',
        ),
    ]
