# Generated by Django 5.1.3 on 2024-12-15 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_order_shipping_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='datetime_ofpayement',
            new_name='datetime_ofpayment',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_address',
        ),
    ]
