# Generated by Django 5.1.3 on 2024-12-15 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_datetime_ofpayement_order_datetime_ofpayment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Canceled', 'Canceled'), ('Completed', 'Completed')], default='Pending', max_length=20),
        ),
    ]
