# Generated by Django 5.1.3 on 2024-12-15 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_order_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='datetime_ofpayment',
            new_name='datetime_ofpayement',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_status',
        ),
    ]
