# Generated by Django 5.1.3 on 2024-12-18 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_wishlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='added_on',
            new_name='added_at',
        ),
    ]
