# Generated by Django 5.1.3 on 2024-12-18 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_offer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='all_products',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='name',
        ),
        migrations.AddField(
            model_name='offer',
            name='discount_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='offer_code',
            field=models.CharField(default='DEFAULT-OFFER-CODE', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='offer',
            name='discount_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
