# Generated by Django 5.1.3 on 2024-12-18 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_offer_delete_discountoffer_remove_order_offer_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='discount_type',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='min_order_value',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='start_date',
        ),
        migrations.AlterField(
            model_name='offer',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
