# Generated by Django 5.1.3 on 2024-12-18 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_remove_offer_discount_type_remove_offer_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='code',
        ),
        migrations.AlterField(
            model_name='offer',
            name='description',
            field=models.CharField(default='No description', max_length=255),
            preserve_default=False,
        ),
    ]
