# Generated by Django 5.1.3 on 2024-12-25 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_order_ordered_productvariant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='product_variant',
        ),
        migrations.DeleteModel(
            name='ProductVariant',
        ),
    ]
