# Generated by Django 5.1.3 on 2024-12-25 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_remove_orderitem_product_alter_order_ordered_and_more'),
        ('core', '0031_remove_orderitem_product_variant_and_more'),
    ]

    operations = [
    ]
