# Generated by Django 5.1.3 on 2025-01-01 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_remove_orderitem_product_variant_orderitem_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='checkout_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.checkoutaddress'),
        ),
    ]
