# Generated by Django 5.1.3 on 2025-01-16 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_alter_order_ordered_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='datetime_ofpayement',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
